### ISSUE TITLE
Stun weapons not working 

### ISSUE THREAD

**Issue by Arcticguy867** [Fancazista/fanca_antitank#1] opened 2024-01-21 06:05 UTC
Certain weapons like stun gun and rubbshotgun , don't do any effect to the player 
 Also certain features like knockout when punching broke

**Comment by Fancazista** [comment] 2024-01-21 09:37
> Certain weapons like stun gun and rubbshotgun , don't do any effect to the player 
>  Also certain features like knockout when punching broke

I already know about it, thanks anyway for reporting it. The problem is that I delete the damage event but from the next version it will no longer be like this so the problem will be solved. 

These days I'm really busy with other things but anyway I have the script there ready to be uploaded.

**Comment by Arcticguy867** [comment] 2024-01-21 09:57
Thnx for the reply waiting for the update

**Comment by Arcticguy867** [comment] 2024-01-26 09:43
> > Certain weapons like stun gun and rubbshotgun , don't do any effect to the player
> > Also certain features like knockout when punching broke
> 
> I already know about it, thanks anyway for reporting it. The problem is that I delete the damage event but from the next version it will no longer be like this so the problem will be solved.
> 
> These days I'm really busy with other things but anyway I have the script there ready to be uploaded.

If u get time please upload the update

**Comment by krasher023** [comment] 2024-02-29 07:46
Any updates on this release? love the script and this fix would be amazing , also using wasabi_ambulance i get all kill logs from weapons saying weapon unkown happening on dc logs + webpanel + txadmin

**Comment by Fancazista** [comment] 2024-02-29 08:24
> Any updates on this release? love the script and this fix would be amazing , also using wasabi_ambulance i get all kill logs from weapons saying weapon unkown happening on dc logs + webpanel + txadmin

This issue is fixed in the update. Before uploading it I should make a small change and it would be ready but at the moment between school, private projects and scripts to deliver to clients I don't have time to follow this resource / publish new scripts.

**Closed as completed** 2024-05-06 17:00 UTC
